[package]
name = "rox"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
num_enum = "0.7.3"
ordered-float = "5.0.0"

[features]
trace = []
